In [1]:
import pandas as pd
import numpy as np
from pymystem3 import Mystem

In [2]:
df = pd.read_parquet("train/train_1.parquet")
df_key = ["отсутствует", "радость", "печаль/грусть", "удивление", "страх", "гнев/злость"]

In [3]:
df = df.drop(['source'], axis=1)

In [4]:
df.head(3)

text labels
0                      Суровый гималайский медведь .     []
1  Так, обнаружено несколько проблем с дисплеем (...     []
2  У меня остается только один вопрос - является ...    [2]

In [5]:
df = df.astype({'labels': 'string'})

In [6]:
df.labels.dtypes

string[python]

In [7]:
print(df.labels[0] == "[]")

True


In [8]:
print(np.array([]))

[]


In [9]:
clear_lst = []
for i in df.labels:
    if i == "[]":
        clear_lst.append(np.array([0]))
    else:
        i = i.replace('[', "").replace(']', "")
        if len(i.split()) == 1:
            clear_lst.append(np.array([int(i) + 1]))
        else:
            clear_lst.append(np.array([int(i[0]) + 1]))

In [10]:
np.array(g)

array([[0],
       [0],
       [3],
       ...,
       [2],
       [0],
       [3]])

In [11]:
df.labels = g

In [12]:
df

text labels
0                         Суровый гималайский медведь .    [0]
1     Так, обнаружено несколько проблем с дисплеем (...    [0]
2     У меня остается только один вопрос - является ...    [3]
3     Забавно как люди в возрасте удивляются входящи...    [1]
4     Издание The Register отмечает, что у владельце...    [0]
...                                                 ...    ...
7523                                Ухаха какая я злая!    [5]
7524                           Я очень рада вас видеть.    [1]
7525                                        Жизнь боль.    [2]
7526                                 - Не удивительно .    [0]
7527                                      Удивительно .    [3]

[7528 rows x 2 columns]

Удаление стоп-слов + токенизация

In [13]:
dirty_x = df['text'].values
dirty_x

array(['Суровый гималайский медведь .',
       'Так, обнаружено несколько проблем с дисплеем (выгорание, странные зеленые полосы), дефекты динамика и некорректная работа Face ID.',
       'У меня остается только один вопрос - является ли этот приступ отчаяния ( а точнее приступ удивления , почему мне не становится лучше , почему мне ничего не помогает ) еще одним испытанием ?',
       ..., 'Жизнь боль.', '- Не удивительно .', 'Удивительно .'],
      dtype=object)

In [14]:
def lemmatiz(text, lst):
    m = Mystem()
    lemmas = m.lemmatize(text)
    lst.append("".join(lemmas))

In [1]:
lem_x = []
for i in dirty_x:
    lemmatiz(i, lem_x)
lem_x

NameError: name 'dirty_x' is not defined

In [16]:
df_clear = pd.read_csv("df_clear")

In [17]:
df_clear

text  \
0             ['суровый', 'гималайский', 'медведь', '.']   
1      [',', 'обнаруживать', 'несколько', 'проблема',...   
2      ['оставаться', 'вопрос', '-', 'являться', 'при...   
3      ['забавно', 'человек', 'возраст', 'удивляться'...   
4      ['издание', 'The', 'Register', 'отмечать', ','...   
...                                                  ...   
15052                              ['ухах', 'злой', '!']   
15053                    ['очень', 'рад', 'видеть', '.']   
15054                             ['жизнь', 'боль', '.']   
15055                          ['-', 'удивительно', '.']   
15056                               ['удивительно', '.']   

                               labels  
0      [1.0, 0.0, 0.0, 0.0, 0.0, 0.0]  
1      [1.0, 0.0, 0.0, 0.0, 0.0, 0.0]  
2      [0.0, 0.0, 0.0, 1.0, 0.0, 0.0]  
3      [0.0, 1.0, 0.0, 0.0, 0.0, 0.0]  
4      [1.0, 0.0, 0.0, 0.0, 0.0, 0.0]  
...                               ...  
15052  [0.0, 0.0, 0.0, 0.0, 0.0, 1.0]  
15053  [0.0, 1.0, 0.0, 0.0, 0.0, 0.0]  
15054  [0.0, 0.0, 1.0, 0.0, 0.0, 0.0]  
15055  [1.0, 0.0, 0.0, 0.0, 0.0, 0.0]  
15056  [0.0, 0.0, 0.0, 1.0, 0.0, 0.0]  

[15057 rows x 2 columns]

In [3]:
from nltk import download
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize
clear_x = []
stop_words = set(stopwords.words('russian'))
#punkt_to_del = ["*",",",".","=","<","<<",">",">>","»","-","—","«"]
for text in lem_x:
    tokens = word_tokenize(text.replace("'", "").replace("\n", ""), 'russian')
    clear_text = []
    for word in tokens:
        if word not in stop_words:
            #if word not in punkt_to_del:
            clear_text.append(word)
    clear_x.append(clear_text)
clear_x

[]

In [29]:
dirty_x[2]

'У меня остается только один вопрос - является ли этот приступ отчаяния ( а точнее приступ удивления , почему мне не становится лучше , почему мне ничего не помогает ) еще одним испытанием ?'

In [31]:
clear_x[2]

['оставаться',
 'вопрос',
 '-',
 'являться',
 'приступ',
 'отчаяние',
 '(',
 'точно',
 'приступ',
 'удивление',
 ',',
 'почему',
 'становиться',
 ',',
 'почему',
 'ничто',
 'помогать',
 ')',
 'испытание',
 '?']

In [21]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Dropout, Flatten, Embedding, Flatten, LSTM, SimpleRNN, GRU, SpatialDropout1D,Bidirectional
from tensorflow.keras import utils
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences

In [22]:
def get_max_length():
    review_length = []
    for review in clear_x:
        review_length.append(len(review))

    return max(review_length)

In [23]:
token = Tokenizer(lower=False)
token.fit_on_texts(clear_x)
x_train = token.texts_to_sequences(clear_x)

max_length = get_max_length()
x_train = pad_sequences(x_train, maxlen=max_length, padding='post', truncating='post')

total_words = len(token.word_index) + 1

In [24]:
data = token.texts_to_matrix(clear_x)

In [94]:
data

array([[0., 0., 1., ..., 0., 0., 0.],
       [0., 1., 1., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 1., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.]])

In [25]:
is0 = 0
is1 = 0
for i in data[0]:
    if i == 0.0:
       is0 += 1
    elif i == 1.0:
        is1 += 1
print(is0, is1)

15686 4


In [26]:
x_train.shape

(7528, 99)

In [27]:
y_train.shape

NameError: name 'y_train' is not defined

In [32]:
x_train

array([[  48, 6343, 1603, ...,    0,    0,    0],
       [   1,  254,  126, ...,    0,    0,    0],
       [ 131,  129,    9, ...,    0,    0,    0],
       ...,
       [  41,   71,    2, ...,    0,    0,    0],
       [   9,   78,    2, ...,    0,    0,    0],
       [  78,    2,    0, ...,    0,    0,    0]])

In [33]:
total_words

15690

In [90]:
y_train = np.array(g)


In [91]:
y_train

array([[0],
       [0],
       [3],
       ...,
       [2],
       [0],
       [3]])

In [36]:
from tensorflow.keras.utils import to_categorical

In [92]:
y_train = to_categorical(y_train)

In [38]:
df_clear = df
df_clear.text = clear_x
df_clear.labels = y_train.tolist()

In [78]:
lem_y = []
for i in y_train:
    lem_y.append(i[0])

In [5]:
lem_y

NameError: name 'lem_y' is not defined

In [7]:
lem_x

[]

In [82]:
df_lemmatiz = {"text": lem_x, "labels": lem_y}

In [83]:
df_lemmatiz = pd.DataFrame(df_lemmatiz)

In [84]:
df_lemmatiz.to_csv('df_lemmatiz', mode='w', index=False)

In [85]:
df_lemmatiz

text  labels
0                       суровый гималайский медведь .\n       0
1     так, обнаруживать несколько проблема с дисплей...       0
2     у я оставаться только один вопрос - являться л...       3
3     забавно как человек в возраст удивляться входи...       1
4     издание The Register отмечать, что у владелец ...       0
...                                                 ...     ...
7523                               ухах какой я злой!\n       5
7524                           я очень рад вы видеть.\n       1
7525                                      жизнь боль.\n       2
7526                               - не удивительно .\n       0
7527                                    удивительно .\n       3

[7528 rows x 2 columns]

In [86]:
x_train.shape

(7528, 99)

In [87]:
np.array(data[0]).shape

(15690,)

In [95]:
data[0]

array([0., 0., 1., ..., 0., 0., 0.])

In [98]:
y_train[0]

array([1., 0., 0., 0., 0., 0.])

In [102]:
model = Sequential()
model.add(Dense(units = 100 , activation = 'relu' , input_dim = data.shape[-1]))
model.add(Dense(units = 50 , activation = 'relu'))
model.add(Dropout(0.5))
model.add(Dense(units = 25 , activation = 'relu'))
model.add(Dense(units = 10 , activation = 'relu'))
model.add(Dropout(0.3))
model.add(Dense(units = 6 , activation = 'softmax'))
model.compile(optimizer = 'adam' , loss = 'categorical_crossentropy' , metrics = ['accuracy'])
model.summary()

Model: "sequential_2"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ dense_10 (Dense)                     │ (None, 100)                 │       1,569,100 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_11 (Dense)                     │ (None, 50)                  │           5,050 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dropout_4 (Dropout)                  │ (None, 50)                  │               0 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_12 (Dense)                     │ (None, 25)                  │           1,275 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_13 (Dense)                     │ (None, 10)                  │             260 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dropout_5 (Dropout)                  │ (None, 10)                  │               0 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_14 (Dense)                     │ (None, 6)                   │              66 │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 1,575,751 (6.01 MB)

 Trainable params: 1,575,751 (6.01 MB)

 Non-trainable params: 0 (0.00 B)

In [103]:
model.fit(data, y_train, epochs=10, batch_size=32, validation_split=0.3)

Epoch 1/10
165/165 ━━━━━━━━━━━━━━━━━━━━ 11s 39ms/step - accuracy: 0.4218 - loss: 1.5941 - val_accuracy: 0.6901 - val_loss: 1.2461
Epoch 2/10
165/165 ━━━━━━━━━━━━━━━━━━━━ 6s 37ms/step - accuracy: 0.6447 - loss: 1.0603 - val_accuracy: 0.7136 - val_loss: 0.9361
Epoch 3/10
165/165 ━━━━━━━━━━━━━━━━━━━━ 6s 34ms/step - accuracy: 0.7315 - loss: 0.7430 - val_accuracy: 0.7207 - val_loss: 0.9071
Epoch 4/10
165/165 ━━━━━━━━━━━━━━━━━━━━ 6s 37ms/step - accuracy: 0.7870 - loss: 0.5714 - val_accuracy: 0.7406 - val_loss: 0.9822
Epoch 5/10
165/165 ━━━━━━━━━━━━━━━━━━━━ 5s 32ms/step - accuracy: 0.8493 - loss: 0.4134 - val_accuracy: 0.7481 - val_loss: 1.1084
Epoch 6/10
165/165 ━━━━━━━━━━━━━━━━━━━━ 12s 40ms/step - accuracy: 0.8692 - loss: 0.3252 - val_accuracy: 0.7406 - val_loss: 1.3471
Epoch 7/10
165/165 ━━━━━━━━━━━━━━━━━━━━ 5s 33ms/step - accuracy: 0.8927 - loss: 0.2775 - val_accuracy: 0.7393 - val_loss: 1.6599
Epoch 8/10
165/165 ━━━━━━━━━━━━━━━━━━━━ 6s 33ms/step - accuracy: 0.8920 - loss: 0.2581 - val_ac

In [104]:
model.save('model_classifire.keras')

In [110]:
import pickle

# saving
with open('tokenizer.pickle', 'wb') as handle:
    pickle.dump(token, handle, protocol=pickle.HIGHEST_PROTOCOL)

In [111]:
import tensorflow as tf

In [112]:
df

text  \
0                    [суровый, гималайский, медведь, .]   
1     [,, обнаруживать, несколько, проблема, дисплей...   
2     [оставаться, вопрос, -, являться, приступ, отч...   
3     [забавно, человек, возраст, удивляться, входит...   
4     [издание, The, Register, отмечать, ,, владелец...   
...                                                 ...   
7523                                    [ухах, злой, !]   
7524                            [очень, рад, видеть, .]   
7525                                   [жизнь, боль, .]   
7526                                [-, удивительно, .]   
7527                                   [удивительно, .]   

                              labels  
0     [1.0, 0.0, 0.0, 0.0, 0.0, 0.0]  
1     [1.0, 0.0, 0.0, 0.0, 0.0, 0.0]  
2     [0.0, 0.0, 0.0, 1.0, 0.0, 0.0]  
3     [0.0, 1.0, 0.0, 0.0, 0.0, 0.0]  
4     [1.0, 0.0, 0.0, 0.0, 0.0, 0.0]  
...                              ...  
7523  [0.0, 0.0, 0.0, 0.0, 0.0, 1.0]  
7524  [0.0, 1.0, 0.0, 0.0, 0.0, 0.0]  
7525  [0.0, 0.0, 1.0, 0.0, 0.0, 0.0]  
7526  [1.0, 0.0, 0.0, 0.0, 0.0, 0.0]  
7527  [0.0, 0.0, 0.0, 1.0, 0.0, 0.0]  

[7528 rows x 2 columns]

In [113]:
test_df = pd.read_parquet("test/test0.parquet")

In [114]:
test_df.text[4]

'Я в мае сдаю, боюсь сейчас) Ну как же, для себя, просто.'

In [115]:
df_key

['отсутствует',
 'радость',
 'печаль/грусть',
 'удивление',
 'страх',
 'гнев/злость']

In [116]:
model = tf.keras.models.load_model('model_classifire.keras')

In [118]:
user_input = input("Введите текст \n")

Введите текст 
 Жизнь боль...


In [119]:
user_input

'Жизнь боль...'

In [120]:
user_list = []
lemmatiz(user_input, user_list)

In [121]:
user_list[0]

'жизнь боль...\n'

In [124]:
# loading
with open('tokenizer.pickle', 'rb') as handle:
    token = pickle.load(handle)

In [125]:
clear_user_input = []
stop_words = set(stopwords.words('russian'))
tokens = word_tokenize(user_list[0].replace("'", "").replace("\n", ""), 'russian')
for word in tokens:
    if word not in stop_words:
        clear_user_input.append(word)
clear_user_input

['жизнь', 'боль', '...']

In [126]:
token.fit_on_texts(clear_user_input)
user_x = token.texts_to_sequences(clear_user_input)
user_x = pad_sequences(user_x, maxlen=max_length, padding='post', truncating='post')


In [127]:
[clear_user_input]

[['жизнь', 'боль', '...']]

In [128]:
user_x = token.texts_to_matrix([clear_user_input])

In [129]:
user_x.shape

(1, 15690)

In [130]:
user_x

array([[0., 0., 0., ..., 0., 0., 0.]])

In [131]:
y_pred = model.predict(user_x)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 164ms/step


In [132]:
y_pred[0][0]

0.0037484854

In [133]:
g = np.where(y_pred[0] == y_pred.max())[0][0]

In [134]:
df_key[g]

'печаль/грусть'